import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import UserContextProvider from "@/context/userContextProvider";
import { ConvexClientProvider } from "@/context/convexProvider";
import Navbar from "@/components/navbar";
import QueryClientProviderWrapper from "@/context/queryClientProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ConvexClientProvider>
        <UserContextProvider>
            <html lang="en">
              <body
              className={`dark antialiased`}
              >
              <QueryClientProviderWrapper>
              <Navbar />
              {children}
          </QueryClientProviderWrapper>
            </body>
            </html>
        </UserContextProvider>
      </ConvexClientProvider>
    </ClerkProvider>
  );
}
